### ISSUE TITLE
Stax: values should not overflow from a multi-screen to a new screen

### ISSUE THREAD

**Issue by emturner** [trilitech/ledger-app-tezos-wallet#180]
see here: https://github.com/trilitech/ledger-app-tezos-wallet/pull/178#discussion_r1439658396

`Commitment` should be moved *entirely* to a new page, since it doesn't fit in the existing one.

Likely related to the logic around declaring a screen with *4* values to be complete.

**Comment by ajinkyaraj-23** [comment]
we are using the ledger provided useCaseReviewStreaming which takes care of display of number of pairs etc.
