### ISSUE TITLE
[BUG] Wrong number of pages

### ISSUE THREAD

**Issue by spalmer25** [trilitech/ledger-app-tezos-wallet#252]
From [Stax tests update #249](https://github.com/trilitech/ledger-app-tezos-wallet/pull/249)
A number of pages has been added to some flow and seems to not correspond to the right number of pages:
![image](https://github.com/user-attachments/assets/a5f18944-3972-404a-a2bb-4b2a5ea18a3b)

**Comment by ajinkyaraj-23** [comment]
This will be fixed by #254
