### ISSUE TITLE
[Flex] Change the icon for flex

### ISSUE THREAD

**Issue by spalmer25** [trilitech/ledger-app-tezos-wallet#253]
An icon for Flex has been added :https://github.com/trilitech/ledger-app-tezos-wallet/pull/247/commits/3d896c78e5dbe85bc2093d2bea95e84828b6e64d#diff-73d2b532f6849f99456a796cfb39971044adb44768440f48fcc05b4b467130db:
![image](https://github.com/user-attachments/assets/1b115a54-3e0f-45f3-8aef-60735fe1f05a)
but it was a default icon while waiting for the new one

**Comment by ajinkyaraj-23** [comment]
Completed.
