### ISSUE TITLE
Fix generated tests for summary pages and warning pages 

### ISSUE THREAD

**Issue by ajinkyaraj-23** [trilitech/ledger-app-tezos-wallet#270]
Warning and summary pages being introduced to solve unlimited scrolling. 
Generated tests fail because of summary page addition.

**Comment by ajinkyaraj-23** [comment]
Can we disable generated tests until we fix our flow for larger transactions?

**Comment by spalmer25** [comment]
> Can we disable generated tests until we fix our flow for larger transactions?

Yes, we'll just have to ping this issue when we disable them to keep tracking the decisions we've made.

**Comment by ajinkyaraj-23** [comment]
Completed
