### ISSUE TITLE
Stax: no speculos events

### ISSUE THREAD

**Issue by spalmer25** [trilitech/ledger-app-tezos-wallet#39]
Speculos does not send data during `URL/events` calls from Stax firmware.

# Goal
On the `home` screen,`URL/events?currentscreenonly=true`:
```json
{
  "events": [
    {"text": "Tezos Wallet", ...}, 
    {"text": "Ready for signing", ...}
  ]
}
```
# Current behaviour
On the `home` screen,`URL/events?currentscreenonly=true`:
```json
{"events": []}
```

**Comment by emturner** [comment]
Yeah, it's a bit of a mess trying to use STAX with OCR (in part because of the all the buttons). Hence why we ended up with ragger

**Comment by ajinkyaraj-23** [comment]
No longer relevant.
