### ISSUE TITLE
Nanox: re-enable generated tests

### ISSUE THREAD

**Issue by emturner** [trilitech/ledger-app-tezos-wallet#43]
Disabled in #22.

The OCR system was completely re-done in the SDK version used in #22 - rather than using OCR, instead the actual bitmaps are extracted from the elf binaries and are used to get info off the screen. (See https://github.com/LedgerHQ/speculos/pull/418 for context)

We will likely have to talk to Ledger to confirm the issue

**Comment by spalmer25** [comment]
After some experimentation, in some cases, the result of `$URL/events?currentscreenonly=true` does not seem to correspond to what is actually on the screen.
For example, if the screen contains a `_`, a `-` or a `~`, then the result is truncated starting from this character.
