### ISSUE TITLE
stax: blindsign using `tz_ui_stream` workflow

### ISSUE THREAD

**Issue by emturner** [trilitech/ledger-app-tezos-wallet#49]
# Goal

Update stax blindsigning to use `tz_ui_stream` workflow, to align with UI of 'clearsigning' workflow.

This will have the benefit of significantly simplifying `apdu_sign.c`, which has a lot of `#ifdefs` for stax vs nano*.

**Comment by ajinkyaraj-23** [comment]
Updated with latest ledger use cases. No longer relevant.
