### ISSUE TITLE
Strange pk display

### ISSUE THREAD

**Issue by spalmer25** [trilitech/ledger-app-tezos-wallet#63]
After a signature request has been rejected, the request to display a public key will display a strange screen.
Example:
 - send `800f000011048000002c800006c18000000080000000`
 - send `800f81005e0300000000000000000000000000000000000000000000000000000000000000006c016e8874874d31c3fbd636e924d5a036a43ec8faa7d0860308362d80d30e01000000000000000000000000000000000000000000ff02000000020316`
 - reject immediately (or at least without going as far as the signature screen)
 - send `8003000011048000002c800006c18000000080000000`
 - tap
# Currently
![Screenshot from 2023-10-16 13-03-27](https://github.com/trilitech/ledger-app-tezos-wallet/assets/81745561/3b67c0bf-ec53-4b3f-a832-e92270645251)
# Expected
![Screenshot from 2023-10-16 13-05-09](https://github.com/trilitech/ledger-app-tezos-wallet/assets/81745561/cbdb6310-f66c-47c5-b117-13f94d58eb90)

**Comment by spalmer25** [comment]
From what I've seen, it seems that the problem comes from the `nbgl` side of `stax`.

**Comment by emturner** [comment]
This is now resolved, after #165
