### ISSUE TITLE
Baking app: document all baking apdus

### ISSUE THREAD

**Issue by emturner** [trilitech/ledger-app-tezos-wallet#78]
In the same style as the wallet app [APDU](https://github.com/trilitech/ledger-app-tezos-wallet/blob/main/app/docs/apdu.md) doc, we should add one for the baking app, describing all the supported codes, and which specific operations are supported.

**Comment by ajinkyaraj-23** [comment]
Not valid now. Baking app is in separate repo. It has its apdu documentation.
