### ISSUE TITLE
Nano: remove gaps between title & icon, title below icon

### ISSUE THREAD

**Issue by emturner** [trilitech/ledger-app-tezos-wallet#80]
# Goal
When displaying title + icon, the icon should appear immediately above the title, and there should be a blank line either side.
The right/left arrows should appear in the middle of the screen, when on the home screen.

## Current state

![screenshot-2023-10-25-12:01:49](https://github.com/trilitech/ledger-app-tezos-wallet/assets/36469783/4f937b90-5cd0-41ac-ac4b-00fc66951595)

## Target state

![screenshot-2023-10-25-12:02:18](https://github.com/trilitech/ledger-app-tezos-wallet/assets/36469783/2c64b064-aa30-43f2-81fc-2b227d04ff62)

**Comment by spalmer25** [comment]
Does 
> When displaying title + icon, the icon should appear immediately above the title

also apply to Nanos device?
