### ISSUE TITLE
stax: update blind signing workflow

### ISSUE THREAD

**Issue by emturner** [trilitech/ledger-app-tezos-wallet#83]
Should we make improvements to the blindsigning flow? 

(Placeholder issue for future blindsigning work).

- Currenlty, we allow blindsigning as a work-around for very large operations (e.g. smart rollup originate).
- Currently, we show `parsing error` on TOO_DEEP or TOO_LARGE - should we offer blindsigning at this point?

**Comment by ajinkyaraj-23** [comment]
Shouldn't the smart rollup originate operation part of baking app?
Also can we enable blind signing on the go? For ex. when we get error like TOO_DEEP or TOO_LARGE, can we immediately offer enable blind signing on next screen and enable it on the spot?

**Comment by ajinkyaraj-23** [comment]
According to feedback from ledger, following changes to blindsigning workflow
1. Only when an error is encountered, give an option to enable blindsigning on the spot, => if enabled go to approve/reject workflow.
2. Keep blindsigning enabled after it is enabled from settings.If blindsigning is enabled from settings, when an error is encountered , we can directly go to approve/reject screens.
